# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CleanupS3Objects < Formula
  desc "CLI tool to delete all versions of objects and delete markers from a S3 bucket"
  homepage "https://github.com/bananaumai/cleanup-s3-objects"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.2/cleanup-s3-objects_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2f14e7cae58b4205e91d5ba6dc39fbd14e6d633730d183abdfa5d4336fd1d81a"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.2/cleanup-s3-objects_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "78227aa025dee0fc4c5419ee761ee1ff420764edb7b36d9ce566f937700cc21f"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.2/cleanup-s3-objects_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "321a53ca37c9e0815771bda23baed6a7c5bdb2ab32c081fd6529d593d3c6eb7a"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.2/cleanup-s3-objects_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "926e7eaf9e6f63417bb72fa614694347e1544ffcde991e18c536409ca74b7022"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
  end
end
