# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewCleanupS3Objects < Formula
  desc "CLI tool to delete all versions of objects and delete markers from a S3 bucket"
  homepage "https://github.com/bananaumai/cleanup-s3-objects"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.1/cleanup-s3-objects_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9bfadd36d91a1a355469539fd362cee358a9398be7bc04f953a6192372c846d0"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.1/cleanup-s3-objects_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5bc35204b5dd6e4be39b018c2467f9b6115780fac81833016c4531b4b4ec59f4"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.1/cleanup-s3-objects_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "896effc0513be4e38dd324dd3b4e9594a28bfe613e2fd45547483fac15ded07b"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bananaumai/cleanup-s3-objects/releases/download/v0.0.1/cleanup-s3-objects_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "036a256465cb5fc450e53d7dfb9cebf912e373e22e5b97ca78fa9cf541802b65"

      def install
        bin.install "cleanup-s3-objects"
      end
    end
  end
end
